services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - db_data:/data
    environment:
      - SQLITE_DB_PATH=/data/database.db
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ENV=${ENV}
      - JWT_ALG=${JWT_ALG}
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${BACKEND_URL}
    ports:
      - "8080:3000"
    restart: always

volumes:
  db_data:
