[project]
name = "agents"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai>=1.37.0",
    "sqlmodel>=0.0.27",
    "shared",
]

[tool.uv.sources]
shared = { workspace = true }
